2025-01-12 01:44:33,760 INFO Start polling
2025-01-12 01:44:33,853 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 01:44:47,782 INFO Update id=557046452 is handled. Duration 367 ms by bot id=7605816882
2025-01-12 01:44:52,850 INFO Update id=557046453 is handled. Duration 107 ms by bot id=7605816882
2025-01-12 01:44:57,011 INFO Update id=557046454 is handled. Duration 181 ms by bot id=7605816882
2025-01-12 01:45:00,811 INFO Update id=557046455 is handled. Duration 233 ms by bot id=7605816882
2025-01-12 01:45:02,894 INFO Update id=557046456 is handled. Duration 125 ms by bot id=7605816882
2025-01-12 01:45:11,930 INFO Update id=557046457 is handled. Duration 2454 ms by bot id=7605816882
2025-01-12 01:46:08,148 INFO Update id=557046458 is handled. Duration 183 ms by bot id=7605816882
2025-01-12 01:48:56,312 INFO Update id=557046459 is not handled. Duration 3 ms by bot id=7605816882
2025-01-12 01:48:56,312 ERROR Cause exception while process update id=557046459 by bot id=7605816882
AttributeError: module 'text' has no attribute 'start'
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 85, in menu
    await msg.answer(text.start.format(name=msg.from_user.full_name), reply_markup=kb.menu)
                     ^^^^^^^^^^
AttributeError: module 'text' has no attribute 'start'
2025-01-12 01:49:08,307 INFO Update id=557046460 is handled. Duration 1397 ms by bot id=7605816882
2025-01-12 01:51:03,077 INFO Update id=557046461 is handled. Duration 227 ms by bot id=7605816882
2025-01-12 01:52:53,624 WARNING Received SIGINT signal
2025-01-12 01:52:53,625 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 01:52:53,625 INFO Polling stopped
2025-01-12 01:55:25,337 INFO Start polling
2025-01-12 01:55:25,440 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 01:56:15,659 WARNING Received SIGINT signal
2025-01-12 01:56:15,660 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 01:56:15,660 INFO Polling stopped
2025-01-12 01:56:17,754 INFO Start polling
2025-01-12 01:56:17,844 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 01:56:22,253 INFO Update id=557046462 is handled. Duration 358 ms by bot id=7605816882
2025-01-12 01:58:27,963 INFO Update id=557046463 is handled. Duration 97 ms by bot id=7605816882
2025-01-12 01:58:31,049 WARNING Received SIGINT signal
2025-01-12 01:58:31,050 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 01:58:31,050 INFO Polling stopped
2025-01-12 01:58:32,776 INFO Start polling
2025-01-12 01:58:32,875 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 01:58:41,546 INFO Update id=557046464 is handled. Duration 360 ms by bot id=7605816882
2025-01-12 01:58:45,784 INFO Update id=557046465 is handled. Duration 158 ms by bot id=7605816882
2025-01-12 02:00:11,915 WARNING Received SIGINT signal
2025-01-12 02:00:11,917 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:00:11,917 INFO Polling stopped
2025-01-12 02:00:14,333 INFO Start polling
2025-01-12 02:00:14,424 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:00:16,752 INFO Update id=557046466 is handled. Duration 427 ms by bot id=7605816882
2025-01-12 02:03:02,384 WARNING Received SIGINT signal
2025-01-12 02:03:02,384 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:03:02,385 INFO Polling stopped
2025-01-12 02:03:05,012 INFO Start polling
2025-01-12 02:03:05,096 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:03:10,085 INFO Update id=557046467 is handled. Duration 396 ms by bot id=7605816882
2025-01-12 02:10:45,708 WARNING Received SIGINT signal
2025-01-12 02:10:45,710 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:10:45,710 INFO Polling stopped
2025-01-12 02:10:47,815 INFO Start polling
2025-01-12 02:10:47,904 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:11:02,909 INFO Update id=557046468 is handled. Duration 11315 ms by bot id=7605816882
2025-01-12 02:11:02,909 INFO Update id=557046469 is handled. Duration 355 ms by bot id=7605816882
2025-01-12 02:11:54,936 WARNING Received SIGINT signal
2025-01-12 02:11:54,936 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:11:54,937 INFO Polling stopped
2025-01-12 02:11:57,168 INFO Start polling
2025-01-12 02:11:57,260 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:12:29,288 WARNING Received SIGINT signal
2025-01-12 02:12:29,289 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:12:29,290 INFO Polling stopped
2025-01-12 02:12:31,276 INFO Start polling
2025-01-12 02:12:31,369 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:12:32,312 WARNING Received SIGINT signal
2025-01-12 02:12:32,313 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:12:32,313 INFO Polling stopped
2025-01-12 02:12:40,176 INFO Start polling
2025-01-12 02:12:40,287 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:12:53,310 INFO Update id=557046470 is handled. Duration 8741 ms by bot id=7605816882
2025-01-12 02:17:30,060 WARNING Received SIGINT signal
2025-01-12 02:17:30,061 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:17:30,062 INFO Polling stopped
2025-01-12 02:17:36,382 INFO Start polling
2025-01-12 02:17:36,484 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:17:48,680 WARNING Received SIGINT signal
2025-01-12 02:17:48,681 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:17:48,681 INFO Polling stopped
2025-01-12 02:17:52,535 INFO Start polling
2025-01-12 02:17:53,960 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:18:03,869 INFO Update id=557046471 is handled. Duration 9150 ms by bot id=7605816882
2025-01-12 02:19:28,629 WARNING Received SIGINT signal
2025-01-12 02:19:28,630 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:19:28,631 INFO Polling stopped
2025-01-12 02:20:46,701 INFO Start polling
2025-01-12 02:20:46,792 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:21:03,164 INFO Update id=557046474 is handled. Duration 12403 ms by bot id=7605816882
2025-01-12 02:21:55,672 WARNING Received SIGINT signal
2025-01-12 02:21:55,673 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:21:55,673 INFO Polling stopped
2025-01-12 02:21:57,783 INFO Start polling
2025-01-12 02:21:57,874 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:22:20,720 INFO Update id=557046475 is not handled. Duration 7695 ms by bot id=7605816882
2025-01-12 02:22:20,720 ERROR Cause exception while process update id=557046475 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 4
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 82, in daily_tasks_handler
    await msg.message.answer(await generate_daily_task(), parse_mode=ParseMode.HTML)
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 4
2025-01-12 02:23:31,413 WARNING Received SIGINT signal
2025-01-12 02:23:31,414 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 02:23:31,414 INFO Polling stopped
2025-01-12 12:30:15,403 INFO Start polling
2025-01-12 12:30:15,524 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:32:21,031 INFO Update id=557046476 is not handled. Duration 10287 ms by bot id=7605816882
2025-01-12 12:32:21,031 ERROR Cause exception while process update id=557046476 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 4
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 82, in daily_tasks_handler
    await msg.message.answer(await generate_daily_task(), parse_mode=ParseMode.HTML)
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 4
2025-01-12 12:38:11,193 WARNING Received SIGINT signal
2025-01-12 12:38:11,194 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:38:11,195 INFO Polling stopped
2025-01-12 12:38:15,014 INFO Start polling
2025-01-12 12:38:15,112 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:39:14,147 WARNING Received SIGINT signal
2025-01-12 12:39:14,149 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:39:14,149 INFO Polling stopped
2025-01-12 12:39:16,585 INFO Start polling
2025-01-12 12:39:16,693 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:39:38,489 INFO Update id=557046477 is handled. Duration 12279 ms by bot id=7605816882
2025-01-12 12:40:47,362 INFO Update id=557046478 is handled. Duration 57873 ms by bot id=7605816882
2025-01-12 12:41:22,539 WARNING Received SIGINT signal
2025-01-12 12:41:22,540 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:41:22,541 INFO Polling stopped
2025-01-12 12:41:25,616 INFO Start polling
2025-01-12 12:41:25,715 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:41:52,774 INFO Update id=557046479 is handled. Duration 1491 ms by bot id=7605816882
2025-01-12 12:42:17,324 INFO Update id=557046480 is handled. Duration 1008 ms by bot id=7605816882
2025-01-12 12:42:23,171 INFO Update id=557046481 is handled. Duration 1408 ms by bot id=7605816882
2025-01-12 12:42:30,529 INFO Update id=557046482 is handled. Duration 1150 ms by bot id=7605816882
2025-01-12 12:42:51,189 INFO Update id=557046483 is handled. Duration 1229 ms by bot id=7605816882
2025-01-12 12:42:56,965 INFO Update id=557046484 is handled. Duration 2016 ms by bot id=7605816882
2025-01-12 12:43:25,494 INFO Update id=557046485 is handled. Duration 24712 ms by bot id=7605816882
2025-01-12 12:44:16,406 INFO Update id=557046486 is handled. Duration 30518 ms by bot id=7605816882
2025-01-12 12:45:35,969 WARNING Received SIGINT signal
2025-01-12 12:45:35,970 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:45:35,971 INFO Polling stopped
2025-01-12 12:45:38,197 INFO Start polling
2025-01-12 12:45:38,294 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:45:59,734 INFO Update id=557046487 is not handled. Duration 1983 ms by bot id=7605816882
2025-01-12 12:45:59,735 ERROR Cause exception while process update id=557046487 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "p" at byte offset 4
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 101, in generate_reply
    await msg.answer(generated_text, parse_mode="HTML")
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "p" at byte offset 4
2025-01-12 12:47:18,659 ERROR Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2025-01-12 12:47:18,660 WARNING Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7605816882)
2025-01-12 12:47:28,247 INFO Connection established (tryings = 1, bot id = 7605816882)
2025-01-12 12:47:29,257 INFO Update id=557046488 is not handled. Duration 1009 ms by bot id=7605816882
2025-01-12 12:47:29,258 ERROR Cause exception while process update id=557046488 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "p" at byte offset 4
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 101, in generate_reply
    await msg.answer(generated_text, parse_mode="HTML")
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "p" at byte offset 4
2025-01-12 12:48:38,283 WARNING Received SIGINT signal
2025-01-12 12:48:38,284 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:48:38,285 INFO Polling stopped
2025-01-12 12:48:40,452 INFO Start polling
2025-01-12 12:48:40,541 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:48:51,311 INFO Update id=557046489 is handled. Duration 968 ms by bot id=7605816882
2025-01-12 12:49:35,491 WARNING Received SIGINT signal
2025-01-12 12:49:35,493 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:49:35,493 INFO Polling stopped
2025-01-12 12:49:37,820 INFO Start polling
2025-01-12 12:49:37,912 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:49:47,764 INFO Update id=557046490 is handled. Duration 1520 ms by bot id=7605816882
2025-01-12 12:50:52,907 INFO Update id=557046491 is not handled. Duration 6353 ms by bot id=7605816882
2025-01-12 12:50:52,907 ERROR Cause exception while process update id=557046491 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 82, in daily_tasks_handler
    await msg.message.answer(await generate_daily_task(), parse_mode=ParseMode.HTML)
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 1
2025-01-12 12:53:22,264 INFO Update id=557046492 is handled. Duration 2052 ms by bot id=7605816882
2025-01-12 12:53:37,190 INFO Update id=557046493 is not handled. Duration 6523 ms by bot id=7605816882
2025-01-12 12:53:37,190 ERROR Cause exception while process update id=557046493 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 82, in daily_tasks_handler
    await msg.message.answer(await generate_daily_task(), parse_mode=ParseMode.HTML)
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 1
2025-01-12 12:53:48,390 WARNING Received SIGINT signal
2025-01-12 12:53:48,391 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:53:48,391 INFO Polling stopped
2025-01-12 12:53:51,351 INFO Start polling
2025-01-12 12:53:51,443 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:53:58,813 INFO Update id=557046494 is not handled. Duration 5615 ms by bot id=7605816882
2025-01-12 12:53:58,813 ERROR Cause exception while process update id=557046494 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 82, in daily_tasks_handler
    await msg.message.answer(await generate_daily_task(), parse_mode=ParseMode.HTML)
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
2025-01-12 12:54:45,708 WARNING Received SIGINT signal
2025-01-12 12:54:45,710 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:54:45,710 INFO Polling stopped
2025-01-12 12:54:47,771 INFO Start polling
2025-01-12 12:54:47,900 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:54:56,949 INFO Update id=557046495 is not handled. Duration 5493 ms by bot id=7605816882
2025-01-12 12:54:56,949 ERROR Cause exception while process update id=557046495 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 82, in daily_tasks_handler
    await msg.message.answer(await generate_daily_task(), parse_mode=ParseMode.HTML)
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
2025-01-12 12:55:06,187 WARNING Received SIGINT signal
2025-01-12 12:55:06,188 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:55:06,188 INFO Polling stopped
2025-01-12 12:55:08,217 INFO Start polling
2025-01-12 12:55:08,320 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:55:16,894 INFO Update id=557046496 is not handled. Duration 5645 ms by bot id=7605816882
2025-01-12 12:55:16,895 ERROR Cause exception while process update id=557046496 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 82, in daily_tasks_handler
    await msg.message.answer(await generate_daily_task(), parse_mode=ParseMode.HTML)
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
2025-01-12 12:55:53,898 WARNING Received SIGINT signal
2025-01-12 12:55:53,899 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:55:53,899 INFO Polling stopped
2025-01-12 12:55:56,045 INFO Start polling
2025-01-12 12:55:56,136 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:56:08,709 INFO Update id=557046497 is not handled. Duration 5424 ms by bot id=7605816882
2025-01-12 12:56:08,709 ERROR Cause exception while process update id=557046497 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='HTML')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
2025-01-12 12:56:24,925 INFO Update id=557046498 is handled. Duration 166 ms by bot id=7605816882
2025-01-12 12:56:29,947 INFO Update id=557046499 is not handled. Duration 3 ms by bot id=7605816882
2025-01-12 12:56:29,947 ERROR Cause exception while process update id=557046499 by bot id=7605816882
AttributeError: module 'text' has no attribute 'start'
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 95, in menu
    await msg.answer(text.start.format(name=msg.from_user.full_name), reply_markup=kb.menu)
                     ^^^^^^^^^^
AttributeError: module 'text' has no attribute 'start'
2025-01-12 12:56:34,846 INFO Update id=557046500 is not handled. Duration 6 ms by bot id=7605816882
2025-01-12 12:56:34,846 ERROR Cause exception while process update id=557046500 by bot id=7605816882
AttributeError: module 'text' has no attribute 'start'
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 95, in menu
    await msg.answer(text.start.format(name=msg.from_user.full_name), reply_markup=kb.menu)
                     ^^^^^^^^^^
AttributeError: module 'text' has no attribute 'start'
2025-01-12 12:56:39,385 INFO Update id=557046501 is handled. Duration 142 ms by bot id=7605816882
2025-01-12 12:56:45,939 INFO Update id=557046502 is not handled. Duration 4719 ms by bot id=7605816882
2025-01-12 12:56:45,939 ERROR Cause exception while process update id=557046502 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='HTML')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
2025-01-12 12:57:18,073 WARNING Received SIGINT signal
2025-01-12 12:57:18,075 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:57:18,075 INFO Polling stopped
2025-01-12 12:57:20,179 INFO Start polling
2025-01-12 12:57:20,277 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:57:27,276 INFO Update id=557046503 is not handled. Duration 5310 ms by bot id=7605816882
2025-01-12 12:57:27,276 ERROR Cause exception while process update id=557046503 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='HTML')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "!doctype" at byte offset 1
2025-01-12 12:58:04,808 WARNING Received SIGINT signal
2025-01-12 12:58:04,809 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:58:04,810 INFO Polling stopped
2025-01-12 12:58:07,799 INFO Start polling
2025-01-12 12:58:07,884 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:58:19,883 INFO Update id=557046504 is not handled. Duration 6430 ms by bot id=7605816882
2025-01-12 12:58:19,883 ERROR Cause exception while process update id=557046504 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h1" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='HTML')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h1" at byte offset 1
2025-01-12 12:59:47,875 WARNING Received SIGINT signal
2025-01-12 12:59:47,876 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 12:59:47,877 INFO Polling stopped
2025-01-12 12:59:50,347 INFO Start polling
2025-01-12 12:59:50,442 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:00:01,704 INFO Update id=557046505 is not handled. Duration 8027 ms by bot id=7605816882
2025-01-12 13:00:01,705 ERROR Cause exception while process update id=557046505 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='HTML')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 1
2025-01-12 13:00:33,395 WARNING Received SIGINT signal
2025-01-12 13:00:33,397 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:00:33,397 INFO Polling stopped
2025-01-12 13:00:35,582 INFO Start polling
2025-01-12 13:00:35,694 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:00:48,170 INFO Update id=557046506 is not handled. Duration 7077 ms by bot id=7605816882
2025-01-12 13:00:48,170 ERROR Cause exception while process update id=557046506 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 1
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='HTML')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h2" at byte offset 1
2025-01-12 13:01:13,490 WARNING Received SIGINT signal
2025-01-12 13:01:13,491 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:01:13,491 INFO Polling stopped
2025-01-12 13:01:15,709 INFO Start polling
2025-01-12 13:01:15,816 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:02:00,796 INFO Update id=557046507 is not handled. Duration 9120 ms by bot id=7605816882
2025-01-12 13:02:00,796 ERROR Cause exception while process update id=557046507 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h3" at byte offset 511
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='HTML')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "h3" at byte offset 511
2025-01-12 13:02:45,713 WARNING Received SIGINT signal
2025-01-12 13:02:45,714 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:02:45,714 INFO Polling stopped
2025-01-12 13:02:48,329 INFO Start polling
2025-01-12 13:02:48,424 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:02:55,796 INFO Update id=557046508 is not handled. Duration 6021 ms by bot id=7605816882
2025-01-12 13:02:55,796 ERROR Cause exception while process update id=557046508 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "p" at byte offset 61
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='HTML')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "p" at byte offset 61
2025-01-12 13:04:42,571 WARNING Received SIGINT signal
2025-01-12 13:04:42,572 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:04:42,572 INFO Polling stopped
2025-01-12 13:04:45,007 INFO Start polling
2025-01-12 13:04:45,126 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:05:04,202 WARNING Received SIGINT signal
2025-01-12 13:05:04,204 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:05:04,204 INFO Polling stopped
2025-01-12 13:05:06,677 INFO Start polling
2025-01-12 13:05:06,856 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:05:17,845 INFO Update id=557046509 is handled. Duration 6443 ms by bot id=7605816882
2025-01-12 13:06:09,813 WARNING Received SIGINT signal
2025-01-12 13:06:09,814 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:06:09,814 INFO Polling stopped
2025-01-12 13:06:11,884 INFO Start polling
2025-01-12 13:06:11,975 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:06:13,518 INFO Update id=557046510 is not handled. Duration 5 ms by bot id=7605816882
2025-01-12 13:06:32,238 INFO Update id=557046511 is not handled. Duration 6362 ms by bot id=7605816882
2025-01-12 13:06:32,239 ERROR Cause exception while process update id=557046511 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '#' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='MarkdownV2')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '#' is reserved and must be escaped with the preceding '\'
2025-01-12 13:07:40,277 WARNING Received SIGINT signal
2025-01-12 13:07:40,278 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:07:40,278 INFO Polling stopped
2025-01-12 13:07:42,572 INFO Start polling
2025-01-12 13:07:42,666 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:07:43,951 WARNING Received SIGINT signal
2025-01-12 13:07:43,952 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:07:43,952 INFO Polling stopped
2025-01-12 13:07:46,322 INFO Start polling
2025-01-12 13:07:46,409 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:07:53,795 INFO Update id=557046512 is not handled. Duration 5520 ms by bot id=7605816882
2025-01-12 13:07:53,796 ERROR Cause exception while process update id=557046512 by bot id=7605816882
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '#' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/main.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/project/handlers.py", line 84, in daily_tasks_handler
    await msg.message.answer(res, parse_mode='MarkdownV2')
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 498, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/Users/kaosintsev/Desktop/AIiEE-chat-bot/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '#' is reserved and must be escaped with the preceding '\'
2025-01-12 13:09:04,286 WARNING Received SIGINT signal
2025-01-12 13:09:04,288 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:09:04,288 INFO Polling stopped
2025-01-12 13:09:06,571 INFO Start polling
2025-01-12 13:09:06,667 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:09:17,689 INFO Update id=557046513 is handled. Duration 8517 ms by bot id=7605816882
2025-01-12 13:10:53,844 WARNING Received SIGINT signal
2025-01-12 13:10:53,845 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:10:53,845 INFO Polling stopped
2025-01-12 13:10:55,946 INFO Start polling
2025-01-12 13:10:56,034 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:11:00,228 INFO Update id=557046514 is handled. Duration 1269 ms by bot id=7605816882
2025-01-12 13:12:41,492 WARNING Received SIGINT signal
2025-01-12 13:12:41,493 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:12:41,494 INFO Polling stopped
2025-01-12 13:12:43,849 INFO Start polling
2025-01-12 13:12:43,938 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:12:51,286 INFO Update id=557046515 is handled. Duration 1338 ms by bot id=7605816882
2025-01-12 13:12:58,002 INFO Update id=557046516 is handled. Duration 998 ms by bot id=7605816882
2025-01-12 13:13:09,125 INFO Update id=557046517 is handled. Duration 2640 ms by bot id=7605816882
2025-01-12 13:13:23,290 INFO Update id=557046518 is handled. Duration 553 ms by bot id=7605816882
2025-01-12 13:13:35,278 INFO Update id=557046519 is handled. Duration 3010 ms by bot id=7605816882
2025-01-12 13:13:41,350 INFO Update id=557046520 is handled. Duration 1099 ms by bot id=7605816882
2025-01-12 13:14:23,187 WARNING Received SIGINT signal
2025-01-12 13:14:23,188 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:14:23,189 INFO Polling stopped
2025-01-12 13:14:25,437 INFO Start polling
2025-01-12 13:14:25,524 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:14:29,274 INFO Update id=557046521 is handled. Duration 921 ms by bot id=7605816882
2025-01-12 13:14:33,490 INFO Update id=557046522 is handled. Duration 805 ms by bot id=7605816882
2025-01-12 13:14:43,723 INFO Update id=557046523 is handled. Duration 3163 ms by bot id=7605816882
2025-01-12 13:15:00,986 INFO Update id=557046524 is handled. Duration 955 ms by bot id=7605816882
2025-01-12 13:15:22,873 WARNING Received SIGINT signal
2025-01-12 13:15:22,874 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:15:22,875 INFO Polling stopped
2025-01-12 13:15:24,992 INFO Start polling
2025-01-12 13:15:25,080 INFO Run polling for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:15:34,421 INFO Update id=557046525 is handled. Duration 7146 ms by bot id=7605816882
2025-01-12 13:15:47,053 INFO Update id=557046526 is handled. Duration 7937 ms by bot id=7605816882
2025-01-12 13:15:55,998 INFO Update id=557046527 is handled. Duration 163 ms by bot id=7605816882
2025-01-12 13:16:04,568 WARNING Received SIGINT signal
2025-01-12 13:16:04,569 INFO Polling stopped for bot @HSEMEMORYBOT id=7605816882 - 'UpgradeYourMemory'
2025-01-12 13:16:04,569 INFO Polling stopped
